index:
    path: /
    controller: App\Controller\DefaultController::index
    methods:    GET

login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: POST

debug:
    path: /debug
    controller: App\Controller\DefaultController::debug
    methods:    GET
