index:
    path: /
    controller: App\Controller\DefaultController::index

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

test:
    path: /api/test
    controller: App\Controller\DefaultController::test

register:
    path: /register
    controller: App\Controller\RegisterController::register

api_login_check:
    path: /api/login_check


#schools
addSchool:
    path: /api/addSchool
    controller: App\Controller\SchoolController::addSchool

getSchools:
    path: /api/schools
    controller: App\Controller\SchoolController::getSchools

school:
    path: /api/school/{id}
    controller: App\Controller\SchoolController::schoolDetails




#classes
addClass:
    path: /api/addClass
    controller: App\Controller\ClassController::addClass

getClass:
    path: /api/classes
    controller: App\Controller\ClassController::getClasses

class:
    path: /api/class/{id}
    controller: App\Controller\ClassController::classDetails


#course
addCourse:
    path: /api/addCourse
    controller: App\Controller\CourseController::addCourse

getCourse:
    path: /api/course/{id}
    controller: App\Controller\CourseController::courseDetails

courses:
    path: /api/courses
    controller: App\Controller\CourseController::getCourses




#teacher
assignTeacher:
    path: /api/assignTeacher
    controller: App\Controller\CourseController::addTeacher

getTeacher:
    path: /api/teacher/{id}
    controller: App\Controller\TeacherController::teacherDetails

teachers:
    path: /api/teachers
    controller: App\Controller\TeacherController::getTeachers



#grades
addGrade:
    path: /api/addGrade
    controller: App\Controller\GradeController::addGrade


#students

