index:
    path: /
    controller: App\Controller\DefaultController::index

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

test:
    path: /api/test
    controller: App\Controller\DefaultController::test

register:
    path: /register
    controller: App\Controller\RegisterController::register

api_login_check:
    path: /api/login_check


#schools
addSchool:
    path: /api/addSchool
    controller: App\Controller\SchoolController::addSchool

getSchools:
    path: /api/Schools
    controller: App\Controller\SchoolController::getSchools

school:
    path: /api/School/{id}
    controller: App\Controller\SchoolController::schoolDetails


#classes
addClass:
    path: /api/addClass
    controller: App\Controller\ClassController::addClass


#course
addCourse:
    path: /api/addCourse
    controller: App\Controller\CourseController::addCourse


#teacher
assignTeacher:
    path: /api/assignTeacher
    controller: App\Controller\CourseController::addTeacher


#grades
addGrade:
    path: /api/addGrade
    controller: App\Controller\GradeController::addGrade

#students

