index:
    path: /
    controller: App\Controller\DefaultController::index

test:
    path: /api/test
    controller: App\Controller\DefaultController::test

register:
    path: /register
    controller: App\Controller\RegisterController::register

api_login_check:
    path: /api/login_check

